version: '3.3'

services:
  backend:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    container_name: dvmn_telegram_bot

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend
    container_name: my_nginx

volumes:
  static_data:
  media_data:
