# Generated by Django 4.2.2 on 2023-06-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='user',
            name='is_speaker',
            field=models.BooleanField(default=False, verbose_name='Спикер'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.user', verbose_name='Спикер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.user', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=250, null=True, verbose_name='О себе'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
