# Generated by Django 4.2.2 on 2023-06-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_about_visitcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitcard',
            options={'verbose_name': 'Визитная карточка', 'verbose_name_plural': 'Визитные карточки'},
        ),
        migrations.AlterField(
            model_name='visitcard',
            name='first_name',
            field=models.CharField(max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='visitcard',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='visitcard',
            name='last_name',
            field=models.CharField(max_length=16, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='visitcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_card', to='backend.user', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='visitcard',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
