# Generated by Django 4.2.2 on 2023-06-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_visitcard_options_alter_visitcard_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=None, verbose_name='Дата проведения'),
            preserve_default=False,
        ),
    ]
